In [1]:
import pandas as pd
import numpy as np
import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation
%matplotlib inline 
sns.set(color_codes=True)

# read the data and store it in df variable
path = 'data_team-9/health_indicators.csv'
df = pd.read_csv(path)

In [2]:
df.head()

,Country_Region,first_1ConfirmedCases,first_1Fatalities,first_10ConfirmedCases,first_50ConfirmedCases,first_100ConfirmedCases,cases_growth,death_growth,Cardiovascular diseases (%),Cancers (%),...,total fertility rate,obesity - adult prevalence rate,school_shutdown_1case,school_shutdown_10case,school_shutdown_50case,school_shutdown_1death,FF_DayOfYear,case1_DayOfYear,case10_DayOfYear,case50_DayOfYear
0,Afghanistan,2020-02-24,2020-03-22,2020-03-14,2020-03-24,2020-03-27,0.174179,0.083333,8.953006,3.372082,...,4.82,5.5,19.0,-0.0,-10.0,-8.0,82.0,55,74.0,84.0
1,Albania,2020-03-09,2020-03-11,2020-03-10,2020-03-16,2020-03-23,0.068699,0.130051,27.016784,13.225390,...,1.53,21.7,2.0,1.0,-5.0,-0.0,71.0,69,70.0,76.0
2,Algeria,2020-02-25,2020-03-12,2020-03-04,2020-03-16,2020-03-21,0.158588,0.228578,17.005476,6.481729,...,2.59,27.4,16.0,8.0,-4.0,-0.0,72.0,56,64.0,76.0
3,Andorra,2020-03-02,2020-03-22,2020-03-17,2020-03-19,2020-03-22,0.082774,0.345238,13.784688,17.879279,...,1.43,25.6,14.0,-1.0,-3.0,-6.0,82.0,62,77.0,79.0
4,Angola,2020-03-20,2020-03-29,NaN,NaN,NaN,0.132143,0.000000,4.480300,3.011632,...,5.96,8.2,4.0,NaN,NaN,-5.0,89.0,80,NaN,NaN

In [3]:
df.shape

(180, 70)

In [4]:
df.info

<bound method DataFrame.info of          Country_Region first_1ConfirmedCases first_1Fatalities  \
0           Afghanistan            2020-02-24        2020-03-22
1               Albania            2020-03-09        2020-03-11
2               Algeria            2020-02-25        2020-03-12
3               Andorra            2020-03-02        2020-03-22
4                Angola            2020-03-20        2020-03-29
..                  ...                   ...               ...
175           Venezuela            2020-03-14        2020-03-27
176             Vietnam            2020-01-23               NaN
177  West Bank and Gaza            2020-03-05        2020-03-26
178              Zambia            2020-03-18        2020-04-02
179            Zimbabwe            2020-03-20        2020-03-23

    first_10ConfirmedCases first_50ConfirmedCases first_100ConfirmedCases  \
0               2020-03-14             2020-03-24              2020-03-27
1               2020-03-10             2020-03-16              2020-03-23
2               2020-03-04             2020-03-16              2020-03-21
3               2020-03-17             2020-03-19              2020-03-22
4                      NaN                    NaN                     NaN
..                     ...                    ...                     ...
175             2020-03-15             2020-03-21              2020-03-26
176             2020-02-06             2020-03-14              2020-03-22
177             2020-03-07             2020-03-22              2020-03-29
178             2020-03-25                    NaN                     NaN
179                    NaN                    NaN                     NaN

     cases_growth  death_growth  Cardiovascular diseases (%)  Cancers (%)  \
0        0.174179      0.083333                     8.953006     3.372082
1        0.068699      0.130051                    27.016784    13.225390
2        0.158588      0.228578                    17.005476     6.481729
3        0.082774      0.345238                    13.784688    17.879279
4        0.132143      0.000000                     4.480300     3.011632
..            ...           ...                          ...          ...
175      0.054474      0.361111                    12.951494     9.719900
176      0.061529           NaN                    16.842832    12.851948
177      0.101132      0.000000                          NaN          NaN
178      0.104540           NaN                     4.074966     3.864070
179      0.111310      0.000000                     6.560883     4.998633

     ...  total fertility rate  obesity - adult prevalence rate  \
0    ...                  4.82                              5.5
1    ...                  1.53                             21.7
2    ...                  2.59                             27.4
3    ...                  1.43                             25.6
4    ...                  5.96                              8.2
..   ...                   ...                              ...
175  ...                  2.26                             25.6
176  ...                  1.77                              2.1
177  ...                   NaN                              NaN
178  ...                  5.49                              8.1
179  ...                  3.93                             15.5

     school_shutdown_1case  school_shutdown_10case  school_shutdown_50case  \
0                     19.0                    -0.0                   -10.0
1                      2.0                     1.0                    -5.0
2                     16.0                     8.0                    -4.0
3                     14.0                    -1.0                    -3.0
4                      4.0                     NaN                     NaN
..                     ...                     ...                     ...
175                    3.0                     2.0                    -4.0
176                   60.0                    46.0                     9.0
177                    NaN                     NaN                     NaN
178                    2.0                    -5.0                     NaN
179                    4.0                     NaN                     NaN

     school_shutdown_1death  FF_DayOfYear  case1_DayOfYear  case10_DayOfYear  \
0                      -8.0          82.0               55              74.0
1                      -0.0          71.0               69              70.0
2                      -0.0          72.0               56              64.0
3                      -6.0          82.0               62              77.0
4                      -5.0          89.0               80               NaN
..                      ...           ...              ...               ...
175                   -10.0          87.0               74              75.0
176                     NaN           NaN               23              37.0
177                     NaN          86.0               65              67.0
178                   -13.0          93.0               78              85.0
179                     1.0          83.0               80               NaN

     case50_DayOfYear
0                84.0
1                76.0
2                76.0
3                79.0
4                 NaN
..                ...
175              81.0
176              74.0
177              82.0
178               NaN
179               NaN

[180 rows x 70 columns]>

In [6]:
df.columns

Index(['Country_Region', 'first_1ConfirmedCases', 'first_1Fatalities',
       'first_10ConfirmedCases', 'first_50ConfirmedCases',
       'first_100ConfirmedCases', 'cases_growth', 'death_growth',
       'Cardiovascular diseases (%)', 'Cancers (%)',
       'Diabetes, blood, & endocrine diseases (%)', 'Respiratory diseases (%)',
       'Liver disease (%)', 'Diarrhea & common infectious diseases (%)',
       'Musculoskeletal disorders (%)', 'HIV/AIDS and tuberculosis (%)',
       'Malaria & neglected tropical diseases (%)',
       'Nutritional deficiencies (%)', 'pneumonia-death-rates',
       'Share of deaths from smoking (%)', 'alcoholic_beverages',
       'animal_fats', 'animal_products', 'aquatic_products,_other',
       'cereals_-_excluding_beer', 'eggs', 'fish,_seafood',
       'fruits_-_excluding_wine', 'meat', 'milk_-_excluding_butter',
       'miscellaneous', 'offals', 'oilcrops', 'pulses', 'spices',
       'starchy_roots', 'stimulants', 'sugar_&_sweeteners', 'treenuts',
       'vegetable_oils', 'vegetables', 'vegetal_products',
       'hospital_beds_per10k', 'hospital_density', 'nbr_surgeons',
       'nbr_obstetricians', 'nbr_anaesthesiologists', 'medical_doctors_per10k',
       'school_closure', 'bcg_coverage', 'bcg_year_delta', 'population',
       'median age', 'population growth rate', 'birth rate', 'death rate',
       'net migration rate', 'maternal mortality rate',
       'infant mortality rate', 'life expectancy at birth',
       'total fertility rate', 'obesity - adult prevalence rate',
       'school_shutdown_1case', 'school_shutdown_10case',
       'school_shutdown_50case', 'school_shutdown_1death', 'FF_DayOfYear',
       'case1_DayOfYear', 'case10_DayOfYear', 'case50_DayOfYear'],
      dtype='object')

In [7]:
df.Country_Region.describe()

count          180
unique         180
top       Cambodia
freq             1
Name: Country_Region, dtype: object